# Cloud Build で作成するコンテナイメージ名。
# ビルド完了後に gcr.io/$PROJECT_ID/$_IMAGE_NAME として push される。
images:
- "gcr.io/$PROJECT_ID/$_IMAGE_NAME"

# 置換変数。`gcloud builds submit --substitutions=...` で上書き可能。
substitutions:
  _IMAGE_NAME: tuna-examples
  _TODO_SERVICE_NAME: tuna-todo
  _PLAYGROUND_SERVICE_NAME: tuna-playground
  _REGION: asia-northeast1
  _PORT: "8888"

steps:
# 1) Dockerfile から単一イメージをビルドする。
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$_IMAGE_NAME", "."]

# 2) 同じイメージを TODO サービスとしてデプロイする。
#    ここで重要なのは `--args`:
#    - Dockerfile の CMD は「デフォルト引数」だが、
#    - Cloud Run の `--args` 指定により起動引数を上書きできる。
#    そのため TODO 用には DB パスを /tmp/todo.sqlite3 にして起動している。
- name: "gcr.io/cloud-builders/gcloud"
  args:
  - "run"
  - "deploy"
  - "$_TODO_SERVICE_NAME"
  - "--image"
  - "gcr.io/$PROJECT_ID/$_IMAGE_NAME"
  - "--platform"
  - "managed"
  - "--region"
  - "$_REGION"
  - "--allow-unauthenticated"
  - "--port"
  - "$_PORT"
  - "--args"
  - "launch,example/server/server.wasm,/tmp/todo.sqlite3"

# 3) 同じイメージを Playground サービスとしてデプロイする。
#    ここでも `--args` で CMD を上書きし、起動対象 wasm と DB を切り替える。
#    つまり「1つのイメージ + 2つの Cloud Run サービス + 起動引数の切替」で
#    TODO / Playground を分けている。
- name: "gcr.io/cloud-builders/gcloud"
  args:
  - "run"
  - "deploy"
  - "$_PLAYGROUND_SERVICE_NAME"
  - "--image"
  - "gcr.io/$PROJECT_ID/$_IMAGE_NAME"
  - "--platform"
  - "managed"
  - "--region"
  - "$_REGION"
  - "--allow-unauthenticated"
  - "--port"
  - "$_PORT"
  - "--args"
  - "launch,example/playground/playground.wasm,/tmp/playground.sqlite3"
