images:
- "gcr.io/$PROJECT_ID/$_SERVICE_NAME"

substitutions:
  _SERVICE_NAME: tuna-server
  _REGION: us-central1

steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$_SERVICE_NAME", "."]

- name: "gcr.io/cloud-builders/gcloud"
  args:
  - "run"
  - "deploy"
  - "$_SERVICE_NAME"
  - "--image"
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME"
  - "--platform"
  - "managed"
  - "--region"
  - "$_REGION"
  - "--allow-unauthenticated"
  - "--port"
  - "8888"
